accordion/urls.py
from django.urls import path

from accordion import views


app_name = 'accordion'

urlpatterns = [
    path('', views.index, name='index'),
]

book/urls.py
from django.urls import path

from book import views


app_name = 'book'

urlpatterns = [
    path('', views.index, name='index'),
    path('get', views.get_books, name='get_books'),
    path('add-likes', views.add_likes, name='add_likes'),
    path('get-top5', views.get_top5, name='get_top5'),
]

myauth/urls.py
from django.urls import path

from myauth import views


app_name = 'myauth'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.sign_up, name='signup'),
    path('login', views.log_in, name='login'),
    path('logout', views.log_out, name='logout'),
    path('home', views.home, name='home'),
]

pewforum/urls.py
from django.urls import path

from pewforum import views


app_name = 'pewforum'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirm', views.confirm, name='confirm'),
    path('change-color/<int:id>', views.change_color, name='change_color')
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story7/', include('pewforum.urls')),
    path('story8/', include('accordion.urls')),
    path('story9/', include('book.urls')),
    path('story10/', include('myauth.urls')),
]

accordion/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models


class Book(models.Model):
    id = models.CharField(max_length=127, primary_key=True)
    cover = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, blank=True)
    publisher = models.CharField(max_length=255, blank=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return f"[{self.likes}]|{self.title} - {self.author}"

myauth/models.py
from django.db import models
from django.contrib.auth.models import User


class MyUser(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    photo = models.URLField()

pewforum/models.py
from django.db import models


class Status(models.Model):
    author = models.CharField(max_length=255)
    topic = models.TextField()
    color = models.CharField(max_length=15)

accordion/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'accordion.html')

book/views.py
from django.shortcuts import render
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse
import requests

from book.models import Book


def index(request):
    return render(request, 'book.html')

def get_books(request):
    if(request.is_ajax()):
        response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + request.GET['keyword'])
        data = response.json()

        for item in data['items']:
            try:
                book = Book.objects.get(id=item['id'])
                likes = book.likes
                
            except:
                likes = 0

            item['volumeInfo']['likes'] = likes 

        return JsonResponse(data)

    else:
        return HttpResponseForbidden()

@csrf_exempt
def add_likes(request):
    if(request.is_ajax()):
        book, created = Book.objects.get_or_create(
            id=request.POST['id'],
            cover=request.POST['cover'],
            title=request.POST['title'],
            author=request.POST['author'],
            publisher=request.POST['publisher'],
        )
        book.likes += int(request.POST['amount'])
        book.save()
        return JsonResponse(book.likes, safe=False)
        
    else:
        return HttpResponseForbidden()

def get_top5(request):
    if(request.is_ajax()):
        books = Book.objects.all().order_by('-likes')[:5]
        book_list = serializers.serialize('json', books)
        return HttpResponse(book_list, content_type="text/json-comment-filtered")
        
    else:
        return HttpResponseForbidden()

myauth/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from myauth.models import MyUser


def index(request):
    if(request.user.is_authenticated):
        return redirect(reverse('myauth:home'))
    
    return render(request, 'myauth.html')

def sign_up(request):
    if(request.user.is_authenticated):
        return redirect(reverse('myauth:home'))

    if(request.method == "GET"):
        return render(request, 'signup.html')
    
    else:
        email = request.POST.get("email")
        photo = request.POST.get("photo")
        username = request.POST.get("username")
        password = request.POST.get("password")

        if(any(not item for item in [email, photo, username, password])):
            messages.error(request, "Datanya belum lengkap pak :(")
            return render(request, 'signup.html')

        try:
            user = User.objects.get(username=username)
            messages.error(request, "usernamenya udah dipake ternyata")
            return render(request, 'signup.html')

        except:
            user = User.objects.create_user(username=username, email=email, password=password)
            my_user = MyUser.objects.create(user=user, photo=photo)

            messages.success(request, "Akun berhasil dibuat")
            return redirect(reverse('myauth:login'))

def log_in(request):
    if(request.user.is_authenticated):
        return redirect(reverse('myauth:home'))

    if(request.method == "GET"):
        return render(request, 'login.html')
    
    else:
        username = request.POST.get("username")
        password = request.POST.get("password")

        # kalo data belum lengkap
        if(not username or not password):
            messages.error(request, "Datanya belum lengkap pak :(")
            return render(request, 'login.html')
        
        # kalo berhasil
        user = authenticate(username=username, password=password)
        if(user is not None):
            login(request, user)
            return redirect(reverse('myauth:home'))

        # kalo ga authenticated
        messages.error(request, "Username atau passwordnya salah tuh")
        return render(request, 'login.html')

def log_out(request):
    logout(request)
    return redirect(reverse('myauth:login'))
    
@login_required(login_url='myauth:login')
def home(request):
    return render(request, 'home.html')

pewforum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
import random

from pewforum.models import Status


def get_random_color_hex():
    r = lambda: random.randint(0, 255)
    return f"#{r():02X}{r():02X}{r():02X}"

def index(request):
    context = {}
    if(request.method == "POST"):
        Status.objects.create(
            author = request.POST.get('name'),
            topic = request.POST.get('status'),
            color = get_random_color_hex(),
        )
    
    context = {
        "datas": Status.objects.all()
    }
    return render(request, "pewforum.html", context)

def confirm(request):
    if(request.method == "GET"):
        return HttpResponse(status=405)
    
    elif(request.method == "POST"):
        context  = {
            'name' : request.POST.get('name'),
            'status' : request.POST.get('status')
        }
        return render(request, "confirm.html", context  )

def change_color(request, id):
    data = get_object_or_404(Status, id=id)
    new_color = data.color
    while(new_color == data.color):
        new_color = get_random_color_hex()

    data.color = new_color
    data.save()
    return redirect('/story7')

myauth/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% block head %}
  {% endblock %}
  <title>Document</title>
</head>
<body>
  {% block body %}
  {% endblock %}
  
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

myauth/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'myauth.css' %}">
{% endblock %}

{% block body %}
  <div>
    <img src="{{ user.myuser.photo }}" alt="">
    <h1>Welcome, {{ user.username }}!</h1>
    <h1>Your email is {{ user.email }}</h1>
    <a href="{% url 'myauth:logout' %}">
      <button class="btn btn-danger">Log Out</button>
    </a>
  </div>

{% endblock %}

myauth/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'myauth.css' %}">
{% endblock %}

{% block body %}

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <script>
          alert("{{ message }}")
        </script>
      {% endfor %}
    </ul>
  {% endif %}

  <div id="form">
    <h3>Log In Form</h3>
    <form action="" method="POST">
      {% csrf_token %}
      <p class="p-row">
        <label for="username">Username: </label>
        <input id="username" name="username" type="text" required> <br/>
      </p>

      <p class="p-row">
        <label for="password">Password: </label>
        <input id="password" name="password" type="password" required> <br/>
      </p>

      <p class="p-row">
        <br/>
        <a href="{% url 'myauth:signup' %}">
          <input type="button" class="btn btn-warning" value="Sign Up">
        </a>
        <input type="submit" value="Log In" class="btn btn-primary" id="login-submit">
      </p>
    </form>
  </div>
{% endblock %}

myauth/templates/myauth.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'myauth.css' %}">
  <title>Auth Ala2</title>
{% endblock %}

{% block body %}
  <div>
    <a href="{% url 'myauth:signup' %}">
      <button type="button" class="btn btn-warning" id="signup-button">Sign Up</button>
    </a>
    <a href="{% url 'myauth:login' %}">
      <button type="button" class="btn btn-primary" id="login-button">Log In</button>
    </a>
  </div>
{% endblock %}

myauth/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'myauth.css' %}">
{% endblock %}

{% block body %}

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <script>
          alert("{{ message }}")
        </script>
      {% endfor %}
    </ul>
  {% endif %}

  <div id="form">
    <h3>Sign Up Form</h3>
    <form action="" method="POST">
      {% csrf_token %}
      <p class="p-row">
        <label for="email">Email: </label>
        <input id="email" name="email" type="email" required> <br/>
      </p>
      <p class="p-row">
        <label for="photo">Photo Link: </label>
        <input id="photo" name="photo" type="url" required> <br/>
      </p>
      <p class="p-row">
        <label for="username">Username: </label>
        <input id="username" name="username" type="text" required> <br/>
      </p>

      <p class="p-row">
        <label for="password">Password: </label>
        <input id="password" name="password" type="password" required> <br/>
      </p>
      <p class="p-row">
        <br/>
        <a href="{% url 'myauth:login' %}">
          <input type="button" class="btn btn-primary" value="Login">
        </a>
        <input type="submit" value="Sign Up" class="btn btn-warning" id="signup-submit">
      </p>
    </form>
  </div>
{% endblock %}

templates/accordion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'accordion.css' %}">
  <title>Alcordion</title>
</head>
<body>
  <div id="main">
    <div class="accordion profile">
      <div class="accordion-bar">
        Profil
        <div class="buttons">
          <button class="up">
            <img src="{% static 'up.png' %}" alt="">
          </button>
          <button class="down">
            <img src="{% static 'down.png' %}" alt="">
          </button>
        </div>
      </div>
      <div class="accordion-content">
        <table>
          <tr>
            <td>Nama</td>
            <td> : Aldi Naufal Fitrah</td>
          </tr>
          <tr>
            <td>Pendidikan</td>
            <td> : Universitas Indonesia</td>
          </tr>
        </table>
      </div>
    </div>
    <div class="accordion activity">
      <div class="accordion-bar">
        Aktivitas saat ini
        <div class="buttons">
          <button class="up">
            <img src="{% static 'up.png' %}" alt="">
          </button>
          <button class="down">
            <img src="{% static 'down.png' %}" alt="">
          </button>
        </div>
      </div>
      <div class="accordion-content" style="display: none;">
        <ul>
          <li>nugas</li>
          <li>stress</li>
          <li>nugas lagi</li>
          <li>ngerjain linebot</li>
          <li>nugas terus</li>
          <li>buat scele notifier</li>
        </ul>
      </div>
    </div>
    <div class="accordion organization">
      <div class="accordion-bar">
        Pengalaman Organisasi
        <div class="buttons">
          <button class="up">
            <img src="{% static 'up.png' %}" alt="">
          </button>
          <button class="down">
            <img src="{% static 'down.png' %}" alt="">
          </button>
        </div>
      </div>
      <div class="accordion-content">
        <ul>
          <li>Pemira Fasilkom</li>
          <li>BEM Fasilkom</li>
          <li>FUKI Fasilkom</li>
        </ul>
      </div>
    </div>
    <div class="accordion achievement">
      <div class="accordion-bar">
        Prestasi
        <div class="buttons">
          <button class="up">
            <img src="{% static 'up.png' %}" alt="">
          </button>
          <button class="down">
            <img src="{% static 'down.png' %}" alt="">
          </button>
        </div>
      </div>
      <div class="accordion-content">
        <ul>
          <li>Juara 1 Kahoot ITF Grand Opening FUKI 2020</li>
          <li>Juara 1 Games sore2 Raker BEM Fasilkom 2020</li>
          <li>Juara 2 Kahoot Raker BEM Fasilkom 2020</li>
          <li>Pemenang Mammamia SBF dan BEM Fasilkom 2020</li>
        </ul>
      </div>
    </div>
    <div class="center">
      <button id="style-modifier">Bosen ah sama warnanya</button>
    </div>
  </div>
  <script src="{% static 'jquery-3.5.0.min.js' %}"></script>
  <script src="{% static 'accordion.js' %}"></script>
</body>
</html>

templates/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bookybase</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'book.css' %}">
  
</head>
<body>
  <input type="text" name="keyword" id="search-box">
  <button id="search-button">Cari</button>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary modal-button" data-toggle="modal" data-target="#exampleModalCenter">
    See Top 5 Books
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Top 5 Books all the time</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <img id="modal-loader" src="{% static 'book-loader.gif' %}" alt="">
          <table id="modal-table" style="display: none">
            <tr>
              <th>Cover</th>
              <th>Title</th>
              <th>Author</th>
              <th>Publisher</th>
              <th>Likes</th>
            </tr>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <img id="loader" src="{% static 'book-loader.gif' %}" alt="">
    <table id="main-table" style="display: none">
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
        <th>Publisher</th>
        <th>Action</th>
      </tr>
      <tr class="not-found" style="display: none;">
        <td><img src="{% static 'default-cover.jpg' %}" alt=""></td>
        <td>Not Found</td>
        <td>Not Found</td>
        <td>Not Found</td>
        <td>Not Found</td>
      </tr>
    </table>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="{% static 'jquery-3.5.0.min.js' %}"></script>
  <script>
    const default_cover = "{% static 'default-cover.jpg' %}";
    const get_books_url = "{% url 'book:get_books' %}?keyword=";
    const add_likes_url = "{% url 'book:add_likes' %}";
    const get_top5_url = "{% url 'book:get_top5' %}";
    const thumblike = "{% static 'thumblike.png' %}";
  </script>
  <script src="{% static 'book.js' %}"></script>
</body>
</html>

templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation page</title>
</head>
<body>
    <form action="{% url 'pewforum:index' %}" method="post">
        {% csrf_token %}
        <label for="id_name">Name: </label>
        <input type="text" name="name" id="id_name" value="{{ name }}" readonly>

        <label for="id_status">Status: </label>
        <textarea name="status" id="id_status" cols="40" rows="10" readonly>{{ status }}</textarea>

        <input type="submit" value="Post it!" id="yes">
    </form>
    <a href="{% url 'pewforum:index' %}"><button>Cancel</button></a>
</body>
</html>

templates/pewforum.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>enViralle</title>
</head>
<body>
  <form action="{% url 'pewforum:confirm' %}" method="post">
    {% csrf_token %}
    <label for="id_name">Name: </label>
    <input type="text" name="name" id="id_name" placeholder="Enter your name" required>
    
    <label for="id_status">Status: </label>
    <textarea name="status" cols="40" rows="10" id="id_status" placeholder="What do you want to share?" required></textarea>
    
    <input type="submit" value="Post it!">
  </form>
  {% for data in datas %}
  <div id="status-wrapper" style="border: 2px solid black; width: fit-content; background-color: {{ data.color }};">
    <a href="{% url 'pewforum:change_color' data.id %}" style="text-decoration: none; color: black;">
      {{ data.author }}: {{data.topic}}
    </a>
  </div>
  {% endfor %}
</body>
</html>